In [2]:
import pandas as pd
import geopandas as gpd

In [9]:
df = gpd.read_file('../data/indicators.json')
df.head()

,geoid,statefp,countyfp,name,level,lss,efd,vfd,lss_score,efd_score,...,uep_cat,mhi_cat,pvt_cat,uep_range,mhi_range,pvt_range,cre,cre_score,cre_cat,geometry
0,1,01,None,Alabama,1,1.778780,1.000000,0.000000,2.338171,1,...,1,0,4,"[ 2.8999999999999999, 3.2999999999999998 ]","[ 44038.0, 53922.0 ]","[ 15.199999999999999, 19.800000000000001 ]",26.757026,3.585412,3,"MULTIPOLYGON (((-88.05338 30.50699, -88.05109 ..."
1,2,02,None,Alaska,1,2.245384,3.396378,0.000000,3.573299,3,...,4,4,1,"[ 4.0999999999999996, 6.0999999999999996 ]","[ 72600.0, 83076.0 ]","[ 10.6, 11.9 ]",20.081772,0.245739,0,"MULTIPOLYGON (((-131.72919 55.54927, -131.7287..."
2,4,04,None,Arizona,1,2.081928,1.603448,1.000000,3.083447,2,...,4,2,3,"[ 4.0999999999999996, 6.0999999999999996 ]","[ 58150.0, 62259.0 ]","[ 13.1, 15.199999999999999 ]",29.327046,4.464477,4,"POLYGON ((-114.81629 32.50804, -114.81432 32.5..."
3,5,05,None,Arkansas,1,1.684156,1.000000,0.000000,2.110694,1,...,2,0,4,"[ 3.2999999999999998, 3.6000000000000001 ]","[ 44038.0, 53922.0 ]","[ 15.199999999999999, 19.800000000000001 ]",25.973100,3.142950,3,"POLYGON ((-94.61783 36.49941, -94.61765 36.499..."
4,6,06,None,California,1,2.721891,4.544063,2.611465,4.413484,5,...,3,4,2,"[ 3.6000000000000001, 4.0999999999999996 ]","[ 72600.0, 83076.0 ]","[ 11.9, 13.1 ]",27.739515,4.062745,4,"MULTIPOLYGON (((-118.60442 33.47855, -118.5987..."

In [6]:
df_gee = pd.read_csv('../data/gee_indicators.csv')
df_gee

,Unnamed: 0,level,index,geoid,statefp,countyfp,name,bbox,geometry,lss,...,lss_cat,lss_range,efd,vfd,efd_score,efd_cat,efd_range,vfd_score,vfd_cat,vfd_range
0,26,1,0,1,1,NaN,Alabama,"[-88.473227, 30.223333999999998, -84.889079999...","MULTIPOLYGON (((-88.053375 30.506987, -88.0510...",1.778780,...,2,"[1.638110007754071, 2.054082956244492]",1.000000,0.000000,1,0,"[0, 2]",0,0,"[0, 2]"
1,36,1,1,2,2,NaN,Alaska,"[-179.148909, 51.214183, 179.77847, 71.365162]","MULTIPOLYGON (((-131.729189 55.549266, -131.72...",2.245384,...,3,"[2.054082956244492, 2.3877670730290137]",3.396378,0.000000,3,1,"[2, 4]",0,0,"[0, 2]"
2,31,1,2,4,4,NaN,Arizona,"[-114.81651, 31.332176999999998, -109.045223, ...","POLYGON ((-114.816294 32.508038, -114.814321 3...",2.081928,...,3,"[2.054082956244492, 2.3877670730290137]",1.603448,1.000000,2,0,"[0, 2]",1,0,"[0, 2]"
3,23,1,3,5,5,NaN,Arkansas,"[-94.617919, 33.004106, -89.644395, 36.4996]","POLYGON ((-94.6178329666013 36.4994141203285, ...",1.684156,...,2,"[1.638110007754071, 2.054082956244492]",1.000000,0.000000,1,0,"[0, 2]",0,0,"[0, 2]"
4,46,1,4,6,6,NaN,California,"[-124.409591, 32.534155999999996, -114.131211,...","MULTIPOLYGON (((-118.604415 33.478552, -118.59...",2.721891,...,4,"[2.3877670730290137, 3.1958368915456874]",4.544063,2.611465,5,2,"[4, 6]",3,1,"[2, 4]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,1917,2,3137,56037,56,37.0,Sweetwater,NaN,"POLYGON ((-110.054384 42.01103, -110.054363 42...",1.682899,...,2,"[1.3328071583139094, 1.6925635015521943]",1.000000,0.000000,1,0,"[0, 2]",0,0,"[0, 2]"
3189,2962,2,3138,56039,56,39.0,Teton,NaN,"POLYGON ((-111.053610326574 44.6662669770011, ...",3.081115,...,4,"[2.324731438522296, 4.525821596244131]",6.875000,0.000000,7,3,"[6, 8]",0,0,"[0, 2]"
3190,2372,2,3139,56041,56,41.0,Uinta,NaN,"POLYGON ((-111.046615849252 41.15604186297939,...",2.075238,...,3,"[1.6925635015521943, 2.324731438522296]",1.000000,0.000000,1,0,"[0, 2]",0,0,"[0, 2]"
3191,2497,2,3140,56043,56,43.0,Washakie,NaN,"POLYGON ((-108.550562 44.16845499999999, -108....",2.231655,...,3,"[1.6925635015521943, 2.324731438522296]",0.000000,0.000000,0,0,"[0, 2]",0,0,"[0, 2]"
3192,1855,2,3141,56045,56,45.0,Weston,NaN,"POLYGON ((-105.080777 43.966216, -105.079281 4...",1.641449,...,2,"[1.3328071583139094, 1.6925635015521943]",0.000000,0.000000,0,0,"[0, 2]",0,0,"[0, 2]"

In [10]:
df.columns

Index(['geoid', 'statefp', 'countyfp', 'name', 'level', 'lss', 'efd', 'vfd',
       'lss_score', 'efd_score', 'vfd_score', 'lss_cat', 'efd_cat', 'vfd_cat',
       'rfr', 'cfr', 'drr', 'rfr_score', 'cfr_score', 'drr_score', 'rfr_cat',
       'cfr_cat', 'drr_cat', 'rfr_range', 'cfr_range', 'drr_range', 'wlf',
       'wlf_score', 'wlf_cat', 'pop', 'pop_score', 'pop_cat', 'uep', 'mhi',
       'pvt', 'uep_score', 'mhi_score', 'pvt_score', 'uep_cat', 'mhi_cat',
       'pvt_cat', 'uep_range', 'mhi_range', 'pvt_range', 'cre', 'cre_score',
       'cre_cat', 'geometry'],
      dtype='object')

In [11]:
df = df[['geoid', 'name', 'level',
       'rfr','rfr_score', 'rfr_cat', 'rfr_range',
       'cfr', 'cfr_score', 'cfr_cat', 'cfr_range',
       'drr', 'drr_score', 'cfr_cat', 'cfr_range',
       'rfr','rfr_score', 'rfr_cat', 'rfr_range',
       'wlf', 'wlf_score', 'wlf_cat', 'wlf_range',
       'pop', 'pop_score', 'pop_cat', 'pop_range',
       'uep','uep_score', 'uep_cat', 'uep_range',
       'mhi', 'mhi_score', 'mhi_cat', 'mhi_range',
       'pvt', 'pvt_score', 'pvt_cat', 'pvt_range',
       'cre', 'cre_score', 'cre_cat', 'cre_range']]

KeyError: "['cre_range', 'wlf_range', 'pop_range'] not in index"

In [16]:
df.astype({'geoid': object}).to_csv('../data/indicator_data.csv')

In [18]:
local_path = '../data/cb_2019_us_state_500k'
state = gpd.read_file(local_path+ '/' + 'cb_2019_us_state_500k.shp')
state = state.set_crs(epsg=4326, allow_override=True)
state = state.to_crs("EPSG:4326")
state.sort_values('GEOID', inplace=True)
# Remove Territories of the United States
state = state.iloc[:51]
state = state[['GEOID', 'STATEFP', 'NAME', 'geometry']]
state.columns = map(str.lower, state.columns)
print("Shape of the dataframe: {}".format(state.shape))
print("Projection of dataframe: {}".format(state.crs))

Shape of the dataframe: (51, 4)
Projection of dataframe: epsg:4326

In [19]:
local_path = '../data/cb_2019_us_county_500k'
county = gpd.read_file(local_path+ '/' + 'cb_2019_us_county_500k.shp')
county = county.set_crs(epsg=4326, allow_override=True)
county = county.to_crs("EPSG:4326")
county.sort_values('GEOID', inplace=True)
# Remove Territories of the United States
county = county[~county['STATEFP'].isin(['60','66','69', '72', '78'])]
county = county[['GEOID', 'STATEFP', 'COUNTYFP', 'NAME', 'geometry']]
county.columns = map(str.lower, county.columns)
print("Shape of the dataframe: {}".format(county.shape))
print("Projection of dataframe: {}".format(county.crs))

Shape of the dataframe: (3142, 5)
Projection of dataframe: epsg:4326

In [23]:
df_geo = pd.concat([state[['geoid', 'name']], county[['geoid', 'name']]])

In [27]:
df_geo['geo_int']=df_geo['geoid'].astype({'geoid': int})

In [35]:
pd.merge(df_geo.drop(columns='name'), df.rename(columns={'geoid': 'geo_int'}), on='geo_int', how='left').drop(columns='geo_int').to_csv('../data/indicator_data.csv')

In [ ]:
['geoid', 'name', 'level', 'lss', 'efd', 'vfd', 
 
 
 
       'lss_score', 'efd_score', 'vfd_score', 'lss_cat', 'efd_cat', 'vfd_cat',
, 'rfr_score', 'cfr_score', 'drr_score', 'rfr_cat',
       'cfr_cat', 'drr_cat', 'rfr_range', 'cfr_range', 'drr_range', 'wlf',
       'wlf_score', 'wlf_cat', 'pop', 'pop_score', 'pop_cat', 'uep', 'mhi',
       'pvt', 'uep_score', 'mhi_score', 'pvt_score', 'uep_cat', 'mhi_cat',
       'pvt_cat', 'uep_range', 'mhi_range', 'pvt_range', 'cre', 'cre_score',
       'cre_cat']